networks:
  sentiric-net:
    name: ${NETWORK_NAME:-sentiric-net}
    driver: bridge

services:
  web-agent-ui:       

      build:
        context: .
        dockerfile: Dockerfile
        args:
          SERVICE_NAME: sentiric-web-agent-ui

      env_file: 
        - ./.env

      # volumes:
      #   - ../sentiric-infrastructure/tls/certs:/etc/sentiric/tls:ro

      ports:
        - "${WEB_AGENT_UI_PORT}:${WEB_AGENT_UI_PORT}"

      networks:
        - sentiric-net
      
      profiles:
        - default
        - ai

      restart: always